version: '2'
services:
    Tweetsrv-app:
        image: Tweetsrv
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://Tweetsrv-postgresql:5432/Tweetsrv
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    Tweetsrv-postgresql:
        extends:
            file: postgresql.yml
            service: Tweetsrv-postgresql
